name: Tests

on: [push]

jobs:

  test-client:
    runs-on: macos-latest
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and run tests
        run: swift test
      - name: Upload report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Report
          path: ~/Library/Developer/Xcode/DerivedData/printds-*/Logs/Test/*.xcresult
